# Site settings
host: 0.0.0.0
title: Founders & Coders - Taster day
host: 0.0.0.0
email: contact@foundersandcoders.org
description: > # this means to ignore newlines until "baseurl:"
  We value diversity. We aim to have a balance of men and women 
  on our courses and encourage applicants from backgrounds that 
  are under-represented in the tech industry. There are no formal 
  educational requirements; our selections are made on aptitude, 
  work ethic and desire to have a positive impact on the world.

